#!/usr/bin/env python3
#
# kas - setup tool for bitbake based projects
#
# Copyright (c) Siemens AG, 2017-2018
#
# SPDX-License-Identifier: MIT

from kas import kas

__license__ = 'MIT'
__copyright__ = 'Copyright (c) Siemens AG, 2017'

kas.main()
